### ISSUE TITLE
Recherche d'une annonce

### ISSUE THREAD

**Issue by faudet78** [faudet78/LetsGo#11]
- Par défaut, aucune recherche ne doit être exécuté lorsque l'on accède au site.

**Comment by azeredudu1** [comment]
expliques parce que je n'ai pas vraiment compris , merci.

**Comment by faudet78** [comment]
Lorsque l'on accède l'application, un message est affiché "Aucun résultat...". Celui-ci ne doit pas apparaitre, seul le formulaire de recherche doit être visible.

**Comment by azeredudu1** [comment]
Detail reglE.

**Comment by faudet78** [comment]
<b>Non résolu</b>
Problème toujours présent, voir le résultat ci-dessous. La liste doit être vide quand on accède au site et quand on est redirigé vers l'accueil.
![recherche](https://cloud.githubusercontent.com/assets/15200690/10863910/d1f37e38-7fdb-11e5-85fb-332a312f582c.jpg)

**Comment by azeredudu1** [comment]
c'est fait

**Comment by faudet78** [comment]
<b>Résolu</b>
