### ISSUE TITLE
Initialisation de la base de données

### ISSUE THREAD

**Issue by faudet78** [faudet78/LetsGo#12]
Exécuter un script qui permet de créer et initialiser toutes la base de données si et seulement si elle n'existe pas.

**Comment by azeredudu1** [comment]
Fait.

**Comment by faudet78** [comment]
<b>Non résolu</b>
Quand on supprime la base de données covoiturage_db, celle-ci n'est pas recréée au démarrage de l'application. Corriger ce problème et vérifier qu'elle n'est récréée que si elle n'existe pas.

Les tables doivent être vides à l'initialisation de la base de données, mise à part la table Role qui doit comprendre la liste des roles utilisateurs. Il y a actuellement des données dans la table Annonce à l'initialisation de la base de données, ce n'est pas un comportement souhaité.

**Comment by azeredudu1** [comment]
Resolu

**Comment by faudet78** [comment]
<b>Résolu</b>
