### ISSUE TITLE
Affichage des annonces

### ISSUE THREAD

**Issue by faudet78** [faudet78/LetsGo#15]
Après la création d'une annonce, quand on fait un recherche d'annonces, les données ne sont pas correctement renseignés dans les résultats de l'annonce ainsi que dans le détail de celle-ci.

**Comment by azeredudu1** [comment]
Details reglE

**Comment by faudet78** [comment]
<b>Non résolu</b>
Problème toujours présent.
Dans le recherche :
![recherche](https://cloud.githubusercontent.com/assets/15200690/10833108/eca5e4ac-7e8f-11e5-8a20-46dc363f8dff.jpg)
Dans le détail de l'annonce :
![details](https://cloud.githubusercontent.com/assets/15200690/10833157/3f272484-7e90-11e5-92ee-3830b5dc398d.jpg)

**Comment by azeredudu1** [comment]
Issue reglee

**Comment by faudet78** [comment]
<b>Résolu</b>
