### ISSUE TITLE
Champs de saisie des adresses

### ISSUE THREAD

**Issue by faudet78** [faudet78/LetsGo#2]
<b>Tâche :</b> Utiliser une fonctionnalité permettant de renseigner les champs de saisie (dans la  recherche et la publication d'une annonce) des adresses et villes en proposant une liste (en auto-completion).
- <i>Pour les champs "Villes", uniquement des villes doivent apparaître dans l'autocompletion.</i>
- <i>Pour les champs "Point de départ/arrivée", uniquement des adresses ou point d'intérêts doivent apparaître dans l'autocompletion.</i>

Utiliser la librairie Google https://developers.google.com/maps/documentation/javascript/places-autocomplete?hl=fr

**Comment by azeredudu1** [comment]
soucis  rencontrE au niveau des adresses , si possible , de m'aider.. Merci

**Comment by faudet78** [comment]
<b>Cette tache m'est assignée.</b>

**Comment by faudet78** [comment]
- L'autocomplete a été ajouté dans les champs de la recherche
- Reste à modifier dans la publication (les lieux doivent dépendre de la ville saisie)

**Comment by faudet78** [comment]
<b>Résolu</b>
