### ISSUE TITLE
Publication d'une annonce

### ISSUE THREAD

**Issue by faudet78** [faudet78/LetsGo#3]
<b>Tâche : </b>Terminer le processus de publication d'une annonce.
- Compléter l'étape 2 avec les informations suivantes : 
  - Marque de la voiture
  - Modèle de la voiture
  - Nombre de portes
  - Climatisation
  - Musique  
  - Animaux autorisés
  - Fumer dans la voiture autorisés
- Déplacer les champs de date et heure dans la partie "Départ"
- Finir la dernière étape de publication d'une annonce.
- Afficher un popup à la fin de la création de l'annonce indiquant que l'annonce va être traitée dans les plus brefs délais.
- Revenir à l'accueil après validation et affichage du popup de prise en compte.

**Comment by faudet78** [comment]
- Déplacement des champs de date et heure dans la partie "Départ"<br>
  <b>Tâche effectuée : Problème de remplissage du champ Heure</b>

**Comment by azeredudu1** [comment]
Les etapes ont ete completees excepter les deux dernieres.
Raisons : toujours en cours de traitement

**Comment by azeredudu1** [comment]
Submit ok. 
Redirection avec message de succes ok.

**Comment by faudet78** [comment]
<b>Validation de l'annonce</b>
- La redirection après validation vers l'accueil du site n'est pas effective. L'utilisateur est actuellement redirigé vers le formulaire de création d'une annonce.

**Comment by azeredudu1** [comment]
redirection , ok..

**Comment by faudet78** [comment]
<b>Non résolu</b>
- Le détail sur le trajet n'est pas champ obligatoire, donc pas de vérification à faire dessus.

**Comment by azeredudu1** [comment]
Resolu

**Comment by azeredudu1** [comment]
Resolu

**Comment by faudet78** [comment]
<b>Résolu</b>
