### ISSUE TITLE
Nettoyage du site 1

### ISSUE THREAD

**Issue by faudet78** [faudet78/LetsGo#6]
- Supprimer l'onglet "Assistance"
- Supprimer les sections "Plus d'infos" et "Ressources", ne conserver que "A propos"

**Comment by faudet78** [comment]
Les sections "Plus d'infos" et "Ressources" n'ont toujours pas été supprimées, ne conserver que "A propos"

**Comment by azeredudu1** [comment]
Issue reglee

**Comment by faudet78** [comment]
<b>Non résolu</b>
Le lien "A propos" doit être sur la même ligne et du même style que les autres liens séparé par le caractère " | ".

Les liens contiennent actuellement le caractère " | " (ex : Conditions générales |), ce qui n'est pas souhaité. Les liens doivent uniquement contenir la chaine de caractère (ex : Conditions générales).

Le footer doit rester en bas du site.

**Comment by azeredudu1** [comment]
detail reglE

**Comment by faudet78** [comment]
<b>Non résolu</b>
- La taille des liens a augmentée, il faut conserver la taille précédente.
- L'hauteur du footer doit se limiter à la taille des liens.
- Le footer n'est toujours pas en base du site, elle reste collé au formulaire de recherche, ce qui n'est pas un comportement souhaité.

**Comment by faudet78** [comment]
<b>Résolu</b>
