### ISSUE TITLE
Amélioration du site

### ISSUE THREAD

**Issue by faudet78** [faudet78/LetsGo#7]
Réduire la taille des différents formulaires (recherche, publication, inscription, connexion, ...)

**Comment by azeredudu1** [comment]
Tache accomplie.

**Comment by faudet78** [comment]
Les tailles sont encore trop grandes. Je m'en occuperai

**Comment by azeredudu1** [comment]
ok, ca marche

**Comment by faudet78** [comment]
<b>Transfèrer vers l'issue "Style du site"</b>
